/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.5.1/userguide/tutorial_java_projects.html
 */

plugins {
    // Apply the java plugin to add support for Java
    java

    // Apply the application plugin to add support for building a CLI application
    application
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    // This dependency is used by the application.
    compile("org.apache.beam:beam-sdks-java-extensions-google-cloud-platform-core:2.15.0")
    compile("org.apache.beam:beam-sdks-java-io-amazon-web-services:2.15.0")
    compile("org.apache.beam:beam-runners-google-cloud-dataflow-java:2.15.0")
    compile("org.apache.beam:beam-runners-direct-java:2.15.0")
    compile("org.apache.beam:beam-sdks-java-io-parquet:2.15.0")
    compile("org.apache.beam:beam-vendor-guava-20_0:0.1")
    compile("org.apache.avro:avro:1.9.1")

    compile("com.google.cloud:google-cloud-bigquery:1.90.0")

    // Use TestNG framework, also requires calling test.useTestNG() below
    testImplementation("org.testng:testng:6.14.3")
}

application {
    // Define the main class for the application
    mainClassName = "bq.avro.App"
}

val test by tasks.getting(Test::class) {
    // Use TestNG for unit tests
    useTestNG()
}
